### ISSUE TITLE
Display error due to incorrect COS endpoint in a more user-friendly way

### ISSUE THREAD

**Issue by kiersten-stokes** [elyra-ai/elyra#1398]
**Describe the issue**
When submitting a pipeline with an Airflow runtime that has a COS endpoint that is either invalid or offline, error message reads "Unexpected end of JSON input" rather than a more insightful message with stack trace.

**To Reproduce**
1. Set up an Airflow runtime configuration with an incorrect COS endpoint
2. Submit a pipeline to this configuration.

**Screenshots or log output**
<img width="311" alt="Screen Shot 2021-03-09 at 9 42 32 AM" src="https://user-images.githubusercontent.com/31816267/110498220-c14a2180-80bc-11eb-9151-b7334f8283bc.png">

**Expected behavior**
Should display a more user-friendly error message. Perhaps try to match the error message for the same situation in a Kubeflow pipeline runtime or otherwise standardize the message between these two runtimes.

**Deployment information**
Describe what you've deployed and how:
 - Elyra version: 2.1

**Comment by ptitzler** [comment]
Were you using 2.1 RC2? This was supposedly fixed by @akchinSTC, no?

**Comment by kiersten-stokes** [comment]
Yeah, using RC2 right now. Just double-checked to confirm I'm still seeing it

**Comment by ptitzler** [comment]
-> https://github.com/elyra-ai/elyra/pull/1377

**Comment by ptitzler** [comment]
Could you please also check whether this works as expected for KFP?

**Comment by kiersten-stokes** [comment]
Alright, sorry everyone! I pulled the latest changes from last night and tested all the above scenarios and they're all displaying a nice error message. Disregard my issue
